### ISSUE TITLE
How to get this running (for morons)?

### ISSUE THREAD

**Issue by PaulTGG** [Rosuav/obs-remote-volume#1]
I've cloned the repo, but when I load the index file, I just see the purple bar at the top with a couple of buttons that don't change anything (as seen here: https://imgur.com/a/JrNJbtr).  What would someone have to do to get it running?  Does it just need a web server with python support?

**Comment by Rosuav** [comment]
Hmm, I'm surprised you don't have a default set of layouts there, so I may have a bug somewhere. But as far as I can tell, you've done everything right. You'll just need to create yourself a layout that has something interesting on it.

Have a quick look at your JavaScript developer console. Are there any errors being reported? It might be that something's crashing out and that's why nothing else is visible.

Incidentally, you don't HAVE to clone the repo yourself; it's directly available at http://vol.rosuav.com/ (deliberately non-SSL to allow it to connect to non-localhost non-SSL websockets) so you might be able to use it from there.

**Comment by PaulTGG** [comment]
heh... I'm one of those "run everything myself with weird setups and make life difficult for everyone else trying to figure out why it doesn't work" people... but here's what I found!

I tried it on Linux and Windows, using Firefox and Chrome/Chromium.  I tried running it locally, and get that Cross-Origin request error you mentioned in index.js.  So I throw it on a web server I have running (httpd on OpenBSD), and I get this in Firefox:

`Loading module from “http://netty/obs/index.js” was blocked because of a disallowed MIME type (“application/octet-stream”).` 

...and similar in Chrome:

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.`

So I guess my particular web server thinks your javascript is binary for some reason?  I'll try to force my server to read it as javascript and see what happens.

**Comment by Rosuav** [comment]
Hah, no problem there. Also, running locally ought to work for the sake of testing anyway, so there should be no fundamental issues with running your own copy.

If you look at that JS script directly, does it have the correct contents? If so, then yeah, it's a question of why your server thinks it's binary. It should be UTF-8 text; in fact, I'm pretty sure it's entirely ASCII, although I won't promise that for the future.

For my testing, I usually use `python3 -m http.server` (optionally with a port number eg `python3 -m http.server 8082`), and that seems to work. Be aware that this is NOT a hardened server, nor a particularly high-performance one, as it's designed for simplicity of local development.

**Comment by PaulTGG** [comment]
Yep, the javascript is fine.  In fact, all of your code is fine, it just turns out I had to explicitly specify "text/javascript" as a MIME type on my server, and now everything works!  Thanks for your help!

So, in case anyone reads this later, the steps to get this working are:

1. Clone the repo and put the files on your web server of choice.
2. Make sure your MIME types are properly configured (assuming it wasn't already done automatically).
3. Profit.

**Comment by PaulTGG** [comment]
Yep, the javascript is fine.  In fact, all of your code is fine, it just turns out I had to explicitly specify "text/javascript" as a MIME type on my server, and now everything works!  Thanks for your help!

So, in case anyone reads this later, the steps to get this working are:

1. Clone the repo and put the files on your web server of choice.
2. Make sure your MIME types are properly configured (assuming it wasn't already done automatically).
3. Profit.

**Comment by Rosuav** [comment]
Awesome, good to know! Have fun with it!

PRs are welcome, as are any "hey, would be real nice if it could do X" comments.
