### ISSUE TITLE
Controlling scene item visibility

### ISSUE THREAD

**Issue by PaulTGG** [Rosuav/obs-remote-volume#2]
Well, since you mention it (heh), it would be nice to be able to control sources as well.  (I know t2t2 used to be able to do that, but I'm not a programmer, so I have no idea how hard it would be in v5!)

**Comment by Rosuav** [comment]
Define "control"? It should be possible to do on the underlying websocket, but the main consideration is the UI. What do you have in mind?

**Comment by PaulTGG** [comment]
I just mean being able to turn them on and off (like the hide/mute buttons in OBS).  It'd definitely mean more screen space, but that might be something to sit in a scrollable iframe (for people who have a zillion sources)?

**Comment by Rosuav** [comment]
Do you mean audio sources? There's a thing for that; it gives you volume and also mute buttons. Do you mean visibility of other elements? I have a stubbed-out "Scene Items" widget that I never got around to finishing, but that would be the place to put it.

**Comment by PaulTGG** [comment]
Sorry, you're right - the audio sources already work beautifully, but it would definitely be awesome to have access to the rest!  I have overlays and videos and stuff that would be nice to be able to control without having to set up scenes for every scenario.

**Comment by Rosuav** [comment]
Okay, cool. Question, though: what information and controls would you want to have available on those? Visibility is easy enough; and obviously the name of the source will be listed. Anything else that should be there as well?

**Comment by PaulTGG** [comment]
Nope, I can't think of anything else that would be functional mid-stream!  (If something goes super wrong with some source properties, or a filter, or a issue with activating/deactivating video sources, I'd imagine folks could just... you know... use OBS... haha)

**Comment by Rosuav** [comment]
Implemented in 671fa9e - lemme know how that goes.

**Comment by PaulTGG** [comment]
*chef's kiss*  That's awesome!
