### ISSUE TITLE
"Mute" button not working, all audio track not showned

### ISSUE THREAD

**Issue by F4GXS** [Rosuav/obs-remote-volume#7]
Hello, i've been using this app for OBS Websocket V5 for few days and some bug are here.

The "Mute" button this not working at all, no movement or reaction seen on OBS when "Mute" button are pressed.
For the audio tracks, i've got only 1 audio track per scene on the Websocket but on my OBS Profil i've got 3 audio tracks per scene minimum (Video, music, mic in, desktop audio, game audio... and so on)

Thanks for the app, keep up working on that, that awesome.

**Comment by Rosuav** [comment]
Thanks! It looks like I somehow never actually tested that code since the protocol v5 update. There were actually three independent, yet related, bugs. Sorry for the issue!

**Comment by Rosuav** [comment]
Although... I'm not 100% sure of the missing audio track issue. If that's still a problem, please reopen this issue, preferably with a screenshot - I usually see the opposite issue, where the remote control has a ton of entries for browser sources that I would prefer not to see.

**Comment by F4GXS** [comment]
I'm going to reopen this issue.
There is the screenshot asked
![Cap_Websocket](https://github.com/Rosuav/obs-remote-volume/assets/55358697/85008ca5-0120-4f94-b620-c19bf9b362c9)
As you can see, on "TEST 1" only 1 audio track is shown but on OBS i've got 3 track (Desktop audio, CAM3 and AUX/MIC)

**Comment by Rosuav** [comment]
Ahh, I think I have an idea what might be wrong here. If you add any other audio sources to OBS, do they show up in the remote control? My current guess is that it's the "global audio devices" that aren't appearing, for whatever reason. Will look into it.

**Comment by F4GXS** [comment]
Yes, i add a random MP3 Music Track into my first scene and it appears after a quick refresh/click of the scene.
![Cap_Websocket2](https://github.com/Rosuav/obs-remote-volume/assets/55358697/be9ce61f-f12e-4a5f-bd5b-54a6617debec)

**Comment by Rosuav** [comment]
Okay, sweet. Incidentally, you seem to have noticed the same thing I did: adding a source doesn't instantly update (it's supposed to). I can fix that one quickly and easily.

As to the globals though - I think I have a solution to that one. Can you confirm please, those are on every scene right?

**Comment by F4GXS** [comment]
Nice to hear some good news and YES, i'm CONFIRM this is on every scene.

**Comment by Rosuav** [comment]
Thanks! I'll get a fix out shortly then.

**Comment by Rosuav** [comment]
Alright, just pushed another change that may be able to fix this. Can you have a look at it and let me know, please? And if there are any bizarre quirks with it (like causing *duplicate* entries now, for example), I definitely want to know.

Thanks for the report!

**Comment by F4GXS** [comment]
Yes, no problem, i'm on it too.
Actualy, nothing change on Websocket Page, doing some page refresh (F5) no change for now.
;)

**Comment by Rosuav** [comment]
Ah, yeah, the public version only updates every fifteen minutes or so (hosted on GitHub Pages as part of this repository).

**Comment by F4GXS** [comment]
Ok,
i can CONFIRM all the bug are now fixed !!!

![Cap_Websocket3](https://github.com/Rosuav/obs-remote-volume/assets/55358697/f97c5cc6-936b-4e8e-8979-30e909fdbd29)

All "Mute" button now worked perfectly !!
All audio track are now showned and worked fine !!
No other bug reported at the time.

Rosuav, you did a GREAT JOB !!!

You can close the issues.

PS : I've got some idea to implement other "element", i'm going to send a "Pull Request" if it possible soon

**Comment by Rosuav** [comment]
Awesome! Thank you so much for (a) bringing the issue, and (b) helping to get it resolved! HUGELY appreciate it.

Further ideas are definitely welcome, whether with or without pull requests.

**Comment by F4GXS** [comment]
Keep thinking about that app !
It help A LOT of people !!

I just think what possibly be cool the app like a "Transition Switcher" or a "Preview/Program Color Button Option" or the possibility to colored a button when something is deactivated, who know, if you have time to program it xD
For now, the app is perfect, non stop playing with it on my smartphone :)

Cheers mate !!
